task_name: scene119

actors:

agents:

  -
    robot_type: tracer_mini
    robot_uid: tracer_mini
    pos:
      ppos:
        p: [0, 0, 3.5]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

  -
    robot_type: starseamap
    robot_uid: starseamap
    pos:
      ppos:
        p: [0, 2, 3.5]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

  -
    robot_type: b2z1
    robot_uid: b2z1
    pos:
      ppos:
        p: [0, -2, 3.5]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[0.418364, 0.465167, 0.492697], [0.435656, 0.249818, 0.127239, -0.855339]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: pose
        params: [[0.868396, 1.09695, 10.703708], [0.454605, 0.234498, 0.125406, -0.85007]]
      width: 512
      height: 512
      fov: 1
      near: 0.01
      far: 100
