task_name: TestEnv-v1
scene:
  stage:
    name: stage_chejian
    file_path: ${ASSET_DIR}/cell_0.glb
    transform:
      position: [0.0, 0.0, 0.0]
      rotation: [0.0, 0.0, 0.0]

actors:
  -
    name: flame_1_1
    render_file_path: ${ASSET_DIR}/flames/flame_pixel_01.obj
    use_visual_as_bounding_box: true
    body_type: static
    transform:
      position: [95.0, 54.0, 0.08]
      rotation: [90.0, 0.0, 0.0]

  -
    name: flame_1_2
    render_file_path: ${ASSET_DIR}/flames/flame_pixel_02.obj
    use_visual_as_bounding_box: true
    body_type: static
    transform:
      position: [94.0, 54.0, 0.0]
      rotation: [90.0, 0.0, 74.5]

  -
    name: flame_1_3
    render_file_path: ${ASSET_DIR}/flames/flame_pixel_01.obj
    use_visual_as_bounding_box: true
    body_type: static
    transform:
      position: [96.25, 54.0, 0.0]
      rotation: [90.0, 0.0, -5.8]

  -
    name: flame_1_4
    render_file_path: ${ASSET_DIR}/flames/flame_pixel_01.obj
    use_visual_as_bounding_box: true
    body_type: static
    transform:
      position: [96.74, 53.09, 0.0]
      rotation: [90.0, 0.0, -116.25]


  -
    name: flame_2_1
    render_file_path: ${ASSET_DIR}/flames/flame_pixel_02.obj
    use_visual_as_bounding_box: true
    body_type: static
    transform:
      position: [95.22, 52.96, 0.0]
      rotation: [90.0, 0.0, -137.0]

  -
    name: flame_2_2
    render_file_path: ${ASSET_DIR}/flames/flame_pixel_01.obj
    use_visual_as_bounding_box: true
    body_type: static
    transform:
      position: [94.07, 52.75, 0.0]
      rotation: [90.0, 0.0, 150.7]

  -
    name: flame_2_3
    render_file_path: ${ASSET_DIR}/flames/flame_pixel_02.obj
    use_visual_as_bounding_box: true
    body_type: static
    transform:
      position: [96.09, 52.6, 0.0]
      rotation: [90.0, 0.0, -56.0]

agents:

  -
    robot_type: tracer_mini
    robot_uid: tracer_mini
    pos:
      ppos:
        p: [0, 0, 3.5]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

  -
    robot_type: starseamap
    robot_uid: starseamap
    pos:
      ppos:
        p: [0, 2, 3.5]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

  -
    robot_type: b2z1
    robot_uid: b2z1
    pos:
      ppos:
        p: [0, -2, 3.5]
        q: [0., 0., 1.5707963268]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

  # -
  #   robot_type: aliengoZ1
  #   robot_uid: robot_dog
  #   pos:
  #     ppos:
  #       p: [3.739549, -2.004936, 3.549874]
  #       q: [0., 0., 1.5707963268]
  #     qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
  #     randp_scale: [0., 0., 0.]
  #     randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  # -
  #   robot_type: drone
  #   robot_uid: drone
  #   pos:
  #     ppos:
  #       p: [0., 0., 1.1]
  #       q: [0., 0., 3.1415926536]
  #     qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
  #     randp_scale: [0., 0., 0.]
  #     randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera_global
      pose:
        type: pose
        params: [[0.418364, 0.465167, 0.492697], [0.435656, 0.249818, 0.127239, -0.855339]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: pose
        params: [[0.868396, 1.09695, 10.703708], [0.454605, 0.234498, 0.125406, -0.85007]]
      width: 512
      height: 512
      fov: 1
      near: 0.01
      far: 100

task_path: hw/cmd/fire.json
